Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "ex-bonus-ansible"

  #Rete privata x collegamento via SSH/Ansible
  config.vm.network "private_network", ip: "192.168.52.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ex-ansible"
    vb.memory = 1024
    vb.cpus = 1
  end

end
