apiVersion: v1
kind: Config
clusters:
- name: minikube-proxy
  cluster:
    server: http://192.168.56.1:8001
users:
- name: proxy-user
  user: {}
contexts:
- name: minikube-proxy
  context:
    cluster: minikube-proxy
    user: proxy-user
current-context: minikube-proxy
