
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "system-dashboard"

  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "system-dashboard"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "provision.sh"
end